import ChooseRoleForm from '@/components/auth/Signup/ChooseRoleForm'
import { Metadata } from 'next'
import React, { Suspense } from 'react'

const page = () => {
    return <Suspense fallback={<div>Loading...</div>}>
        <ChooseRoleForm />
    </Suspense>
}

export default page

export const metadata: Metadata = {
    title: "Choose Role | MyHome",
    description: "Generated by create next app",
};