import ChooseRoleForm from '@/components/auth/Signup/ChooseRoleForm'
import { Metadata } from 'next'
import React from 'react'

const page = () => {
    return <ChooseRoleForm />
}

export default page

export const metadata: Metadata = {
    title: "Choose Role | MyHome",
    description: "Generated by create next app",
};