// import { metadata } from '@/app/layout'
import TermsConditions from "@/components/web-pages/settings/terms-condition";
import { Metadata } from "next";
import React from "react";

const page = () => {
  return (
    <div>
      <TermsConditions />
    </div>
  );
};

export default page;
export const metadata: Metadata = {
  title: "Terms & Conditions | Westfert Fertilisers",
  description: "Generated by create next app",
};
