import SignInForm from '@/components/auth/Login'
import { Metadata } from 'next'
import React from 'react'

const page = () => {
  return (
    <div>
         <SignInForm />
    </div>
  )
}

export default page

export const metadata: Metadata = {
  title: "Login | Westfert Fertilisers",
  description: "Generated by create next app",
};